### PR TITLE
Fix code sniffer errors

### PR DESCRIPTION
**Pull request by christophherr**
Warnings about "Line exceeding 85 characters" are still being shown.
Related issue: #4

### CODE REVIEW

**Comment by christophherr** [comment]
The three options would be to try to reduce the characters per line, exclude the line length rule or add your own line length standard.

**Comment by ankitjain28may** [comment]
@christophherr It can also be fixed like you can break line from commas or you can use `.` to concat a large statement by breaking it into smaller sub strings.

**Comment by christophherr** [comment]
@ankitjain28may No problem. Just wanted to know how you want to handle it.

**Comment by ankitjain28may** [comment]
@christophherr No problem, Thanks for fixing this, Would you like to write the tests for the project ?

**Comment by christophherr** [comment]
@ankitjain28may Thanks. I'll see if I can add some tests.

**Comment by ankitjain28may** [comment]
@christophherr You can use Laravel/dusk to write tests for the project.

**Pull request merged**
